// conversation-state.enum.ts
export enum ConversationState {
  NONE = 'NONE',
  HORARIO_FUNCIONAMENTO = 'HORARIO_FUNCIONAMENTO',
  AGENDAMENTO_ESCOLHER_SERVICO = 'AGENDAMENTO_ESCOLHER_SERVICO',
  AGENDAMENTO_ESCOLHER_DATA = 'AGENDAMENTO_ESCOLHER_DATA',
  AGENDAMENTO_ESCOLHER_HORARIO = 'AGENDAMENTO_ESCOLHER_HORARIO',
  AGENDAMENTO_CONFIRMAR = 'AGENDAMENTO_CONFIRMAR',
  CONSULTA_AGENDAMENTOS = 'CONSULTA_AGENDAMENTOS',
  FEEDBACK_MENU = 'FEEDBACK_MENU',
  FEEDBACK_AVALIACAO = 'FEEDBACK_AVALIACAO',
  FEEDBACK_COMENTARIO = 'FEEDBACK_COMENTARIO'
}